variables:
  DOCKER_REGISTRY: https://gcr.io
  DOCKER_REGISTRY_URL: gcr.io/ecad-auth

stages:
  - build
  - test

test-auth:
  stage: test
  image: golang:alpine
  services:
    - postgres:latest
  script:
    - mkdir -p /go/src/git.ecadlabs.com/ecad/auth
    - cp -r * /go/src/git.ecadlabs.com/ecad/auth
    - cd /go/src/git.ecadlabs.com/ecad/auth/intergationtesting
    - go test -db "postgres://postgres@postgres/postgres?connect_timeout=10&sslmode=disable"

docker-build-auth:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - echo ${GOOGLE_GCR_KEY} | docker login -u _json_key --password-stdin ${DOCKER_REGISTRY}
    - >
      docker build 
      -t "${DOCKER_REGISTRY_URL}/auth:${CI_COMMIT_REF_NAME}" 
      -t "${DOCKER_REGISTRY_URL}/auth:latest" 
      .
    - docker push "${DOCKER_REGISTRY_URL}/auth:${CI_COMMIT_REF_NAME}"
    - docker push "${DOCKER_REGISTRY_URL}/auth:latest"

build-auth-api-docs:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - echo ${GOOGLE_GCR_KEY} | docker login -u _json_key --password-stdin ${DOCKER_REGISTRY}
    - >
      docker build 
      -t "${DOCKER_REGISTRY_URL}/auth_api_docs:${CI_COMMIT_REF_NAME}" 
      -t "${DOCKER_REGISTRY_URL}/auth_api_docs:latest" 
      .
    - docker push "${DOCKER_REGISTRY_URL}/auth_api_docs:${CI_COMMIT_REF_NAME}"
    - docker push "${DOCKER_REGISTRY_URL}/auth_api_docs:latest"
