variables:
  DOCKER_REGISTRY: https://gcr.io
  DOCKER_REGISTRY_URL: gcr.io/ecad-auth

stages:
  - build
  - test

docker-build-auth:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - echo ${GOOGLE_GCR_KEY} | docker login -u _json_key --password-stdin ${DOCKER_REGISTRY}
    - docker build -t "${DOCKER_REGISTRY_URL}/postgres-auth:${CI_COMMIT_REF_NAME:0:8}-${CI_COMMIT_SHA:0:8}" .
    - docker push "${DOCKER_REGISTRY_URL}/postgres-auth:${CI_COMMIT_REF_NAME:0:8}-${CI_COMMIT_SHA:0:8}"

test-auth:
  stage: test
  image: golang:alpine
  services:
    - postgres:latest
  script:
    - mkdir -p /go/src/git.ecadlabs.com/ecad/auth
    - cp -r * /go/src/git.ecadlabs.com/ecad/auth
    - cd /go/src/git.ecadlabs.com/ecad/auth
    - go test -db "postgres://postgres@postgres/postgres?connect_timeout=10&sslmode=disable"