jwt_secret: secret
email:
  from_address: auth@ecadlabs.com
  driver: debug,
  config:
    address: smtp.gmail.com:587
    user: auth@ecadlabs.com
  template:
    app_name: ECAD Portal
    reset_url_prefix: http://localhost:8000/reset_password/
    update_email_prefix: http://localhost:8000/update_email/
    support_email: support@domain.com
