version: '3'
services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.6.0
    volumes:
      - ./envoy/:/etc/envoy
    command: /usr/local/bin/envoy -c /etc/envoy/envoy_dev.yaml
    ports:
      - '8000:10000'
      - '9901:9901'

  db:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth
      - POSTGRES_DB=auth

  auth:
    build:
      context: .
    depends_on:
      - db
    environment:
      - AUTH_ADMIN_EMAIL=admin@admin
      - AUTH_ADMIN_PASSWORD=admin
      - AUTH_ADMIN_ROLES=admin
    entrypoint: /app/auth
    command:
      - -db
      - 'postgres://auth:auth@db/auth?connect_timeout=10&sslmode=disable'
      - -base
      - 'http://localhost:8000/api/v1'
      - -bootstrap
      - /app/bootstrap.yaml
      - -namespace
      - com.ecadlabs.auth
      - -c
      - /app/config.yaml
      - -r
      - /app/rbac.yaml
    volumes:
      - ./config.example.yaml:/app/config.yaml

  apidocs:
    build:
      context: apidocs/
    depends_on:
      - envoy
    command: /bin/bash -c "nginx -g 'daemon off;'"

volumes:
  node_modules_volume:
