version: 2

defaults: &defaults
    working_directory: ~/auth
    docker:
      - image: circleci/node:10-browsers-legacy

jobs:
  webapp-test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "webapp/package-lock.json" }}
      - run:
          name: install-dependencies
          command: cd webapp && npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "webapp/package-lock.json" }}
          paths:
            - ./webapp/node_modules
      # - run:
      #     name: lint
      #     command: cd webapp && npm run lint
      # - run:
      #     name: build
      #     command: cd webapp && npm run build
      # - run:
      #     name: test
      #     command: cd webapp && npm run test-ci
      - persist_to_workspace:
          root: ~/auth
          paths: .
  webapp-deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/auth
      - run:
          name: Authenticate with registry
          command: cd webapp/dist/ecad-angular-auth && echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: cd webapp/dist/ecad-angular-auth && npm publish
            
workflows:
  version: 2
  test:
    jobs:
      - webapp-test
  test-deploy:
    jobs:
      - webapp-test
          # filters:
          #   tags:
          #     only: /^v.*/
      - webapp-deploy:
          requires:
            - webapp-test
          # filters:
          #   tags:
          #     only: /^v.*/
          #   branches:
          #     ignore: /.*/