version: 2
jobs:
  test:
    working_directory: ~/webapp
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: cd webapp && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./webapp/node_modules
      - run:
          name: test
          command: cd webapp && npm run test-ci
workflows:
  version: 2
  test:
    jobs:
      - test