---
- name: setup solarcontroller auth & postgres service
  hosts: solarcontrol.ecadlabs.com
  become: yes

  vars:
    pip_install_packages:
      - name: docker
    docker_registry: gcr.io/ecad-auth/
    git_tag: 2-create-2557feee
    pg_tag: 10.3
    docker_network_name: solarcontrol

  roles:
  - role: geerlingguy.repo-epel
  - role: geerlingguy.pip
  - role: geerlingguy.docker

  tasks:
  - name: Create docker network for all containers to be in
    docker_network:
      name: solarcontrol

  - name: Create auth-postgres volume
    docker_volume:
      state: present
      name: auth-pgdata

  - name: Create auth-postgres container
    docker_container:
      name: auth-postgres
      state: present
      image: "postgres:{{ pg_tag }}"
      networks:
        - name: "{{ docker_network_name }}"
      volumes:
        - auth-pgdata:/var/lib/postgresql/data

  - name: Render auth-postgres.service unit file
    template:
      src: auth-postgres.service.j2
      dest: /etc/systemd/system/auth-postgres.service
      owner: root
      group: root

  - name: Enable & start auth-postgres.service
    systemd:
      name: auth-postgres
      state: started
      enabled: yes
      daemon_reload: yes

  - name: Create auth container
    docker_container:
      name: auth
      state: present
      image: "{{ docker_registry }}postgres-auth:{{ git_tag }}"
      networks:
        - name: "{{ docker_network_name }}"
      volumes:
        - /var/lib/solarcontrol:/data

  - name: Render auth.service unit file
    template:
      src: auth.service.j2
      dest: /etc/systemd/system/auth.service
      owner: root
      group: root

  - name: Enable & start auth.service
    systemd:
      name: auth
      enabled: yes
      daemon_reload: yes
      state: started